### ISSUE TITLE
Feature request: Export note to MD and TXT (bulk and individual)

### ISSUE THREAD

**Issue by andreasmjg** [etesync/etesync-notes#50] opened 2020-11-17 07:48 UTC
This is normally one of the key decision points to make me decide to use anything: proper export function. 

I suggest exporting to markdown and a text file and one with HTML tags. Both option for one note and for all / many notes (select with checkboxes). 

Thanks!
Andreas

**Comment by tasn** [comment] 2020-11-19 08:56
It's a duplicate of #24, so I'm closing it. Though it's definitely something we would like to have!

**Closed by tasn** 2020-11-19 08:56 UTC
